services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: ${MY_DB_USERNAME}
      POSTGRES_PASSWORD: ${MY_DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "5432:5432"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:8000/library
      SPRING_DATASOURCE_USERNAME: ${MY_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MY_DB_PASSWORD}
    restart: always

volumes:
  pgdata:
